trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrUsername: 'sppringg'
  acrPassword: 'e3/m6Lym5Ov/y5J4gGuHu3fwR63QKle2vJqP9TMGfw+ACRCRg7Gx'
  acrRegistry: 'sppringg.azurecr.io'
  dockerImageName: 'spring-boot'

stages:
- stage: BuildAndPush
  jobs:
  - job: BuildAndPush
    steps:
    - script: echo 'Starting Maven build and Docker push'
      displayName: 'Starting Maven Build and Docker Push'

    - task: Setup Java
      inputs:
        versionSpec: '8'
        addToPath: true

    - task: Maven@3
      inputs:
        mavenVersion: '3.9.3'

    - script: |
        # First Stage: Build Spring Boot Project with Maven
        mvn clean package
      displayName: 'Build Spring Boot Project'

    - task: UseDotNet@2
      inputs:
        version: '2.x'
        packageType: 'sdk'

    - script: |
        # Second Stage: Build Docker Image
        docker build -f Dockerfile -t $(dockerImageName):$(Build.BuildId) .
      displayName: 'Build Docker Image'

    - script: |
        # Login to Docker Registry (ACR)
        docker login -u $(acrUsername) -p $(acrPassword) $(acrRegistry)

        # Push Docker Image to ACR
        docker tag $(dockerImageName):$(Build.BuildId) $(acrRegistry)/$(dockerImageName):$(Build.BuildId)
        docker push $(acrRegistry)/$(dockerImageName):$(Build.BuildId)
      displayName: 'Push Docker Image to ACR'

    - script: echo 'Maven build and Docker push completed successfully!'
      displayName: 'Maven Build and Docker Push Complete'
