apiVersion: v1
kind: Service
metadata:
  name: spg-boot
spec:
  selector:
    app: spg-boot
  ports:
    - protocol: TCP
      port: 80  # Service port
      targetPort: 8080  # Target port of your application
  type: LoadBalancer  # Use LoadBalancer for public access, adjust as needed
